spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: Search
          uri: lb://Search
          predicates:
            - Path=/search/**
          filters:
            - RewritePath=/search/(?<segment>.*),/$\{segment}
        - id: Management
          uri: lb://Management
          predicates:
            - Path=/management/**
          filters:
            - RewritePath=/management/(?<segment>.*),/$\{segment}
        - id: Code
          uri: lb://Code
          predicates:
            - Path=/code/**
          filters:
            - RewritePath=/code/(?<segment>.*),/$\{segment}
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allowed-credentials: true

server:
  port: 9000